#!/usr/bin/env python3
"""
Generates auth/supabase-config.js from CI environment variables,
and stamps service-worker.js with an auto-incrementing cache version.
Called by GitHub Actions deploy.yml — do not run manually.

Required env vars (set as REPOSITORY secrets in GitHub):
  SUPABASE_URL      https://xxxx.supabase.co
  SUPABASE_ANON     your-anon-public-key
  VAPID_PUBLIC_KEY  your VAPID EC public key (safe to embed, not secret)

Auto-injected by GitHub Actions (no config needed):
  GITHUB_SHA        full commit SHA — first 7 chars used as build tag
"""
import json
import os
import re
import sys
from datetime import date

url          = os.environ.get("SUPABASE_URL",     "").strip()
anon         = os.environ.get("SUPABASE_ANON",    "").strip()
vapid_pubkey = os.environ.get("VAPID_PUBLIC_KEY", "").strip()

# ── Validate ──────────────────────────────────────────────────────────────────
if not url.startswith("https://"):
    print("::error::SUPABASE_URL is missing or not a valid https URL.", file=sys.stderr)
    print("  Got: " + repr(url[:30]), file=sys.stderr)
    print("  Fix: repo Settings → Secrets → Actions → New repository secret → SUPABASE_URL", file=sys.stderr)
    sys.exit(1)

if len(anon) < 20:
    print("::error::SUPABASE_ANON is missing or too short.", file=sys.stderr)
    print("  Fix: repo Settings → Secrets → Actions → New repository secret → SUPABASE_ANON", file=sys.stderr)
    sys.exit(1)

if len(vapid_pubkey) < 10:
    print("::warning::VAPID_PUBLIC_KEY is missing — push notifications will not work.", file=sys.stderr)
    print("  Fix: repo Settings → Secrets → Actions → New repository secret → VAPID_PUBLIC_KEY", file=sys.stderr)

# ── Generate ──────────────────────────────────────────────────────────────────
lines = [
    "// Auto-generated by GitHub Actions — do not commit or edit manually",
    "var SUPABASE_URL      = " + json.dumps(url)          + ";",
    "var SUPABASE_ANON     = " + json.dumps(anon)         + ";",
    "var VAPID_PUBLIC_KEY  = " + json.dumps(vapid_pubkey) + ";",
    "var _supabase = (function () {",
    "  if (!SUPABASE_URL.startsWith('https://') || SUPABASE_ANON.length < 20) {",
    "    console.error('[LM] supabase-config.js: credentials not configured correctly.');",
    "    return undefined;",
    "  }",
    "  return window['supabase'].createClient(SUPABASE_URL, SUPABASE_ANON, {",
    "    auth: {",
    "      persistSession    : true,",
    "      autoRefreshToken  : true,",
    "      detectSessionInUrl: true",
    "    }",
    "  });",
    "}());",
    "",
]

content = "\n".join(lines)

with open("auth/supabase-config.js", "w") as f:
    f.write(content)

print("✅  auth/supabase-config.js generated (" + str(len(content)) + " bytes)")
print("    URL: " + url[:45] + "...")

# ── Stamp service-worker.js with auto cache version ──────────────────────────
sha          = os.environ.get("GITHUB_SHA", "local")[:7]
build_date   = date.today().strftime("%Y%m%d")
cache_version = "lm-v" + build_date + "." + sha

sw_path = "service-worker.js"
with open(sw_path, "r") as f:
    sw = f.read()

sw_patched = re.sub(
    r"const CACHE_VERSION = 'lm-v[^']*';",
    "const CACHE_VERSION = '" + cache_version + "';",
    sw
)

with open(sw_path, "w") as f:
    f.write(sw_patched)

print("✅  service-worker.js cache version → " + cache_version)
