#!/usr/bin/env python3
"""
Generates auth/supabase-config.js from CI environment variables.
Called by GitHub Actions deploy.yml — do not run manually.

Required env vars (set as REPOSITORY secrets in GitHub):
  SUPABASE_URL   https://xxxx.supabase.co
  SUPABASE_ANON  your-anon-public-key
"""
import os
import sys

url  = os.environ.get("SUPABASE_URL",  "").strip()
anon = os.environ.get("SUPABASE_ANON", "").strip()

# ── Validate ──────────────────────────────────────────────────────────────────
if not url.startswith("https://"):
    print("::error::SUPABASE_URL is missing or not a valid https URL.", file=sys.stderr)
    print("  Got: " + repr(url[:30]), file=sys.stderr)
    print("  Fix: repo Settings → Secrets → Actions → New repository secret → SUPABASE_URL", file=sys.stderr)
    sys.exit(1)

if len(anon) < 20:
    print("::error::SUPABASE_ANON is missing or too short.", file=sys.stderr)
    print("  Fix: repo Settings → Secrets → Actions → New repository secret → SUPABASE_ANON", file=sys.stderr)
    sys.exit(1)

# ── Generate ──────────────────────────────────────────────────────────────────
lines = [
    "// Auto-generated by GitHub Actions — do not commit or edit manually",
    "var SUPABASE_URL  = '" + url  + "';",
    "var SUPABASE_ANON = '" + anon + "';",
    "var _supabase = (function () {",
    "  if (!SUPABASE_URL.startsWith('https://') || SUPABASE_ANON.length < 20) {",
    "    console.error('[LM] supabase-config.js: credentials not configured correctly.');",
    "    return undefined;",
    "  }",
    "  return window['supabase'].createClient(SUPABASE_URL, SUPABASE_ANON, {",
    "    auth: {",
    "      persistSession    : true,",
    "      autoRefreshToken  : true,",
    "      detectSessionInUrl: true",
    "    }",
    "  });",
    "}());",
    "",
]

content = "\n".join(lines)

with open("auth/supabase-config.js", "w") as f:
    f.write(content)

print("✅  auth/supabase-config.js generated (" + str(len(content)) + " bytes)")
print("    URL: " + url[:45] + "...")
