// ─── Supabase Client Config ────────────────────────────────────────────────────
// LOCAL DEV: Replace the two values below with your real project credentials.
//   Supabase Dashboard → Settings → API → Project URL  &  anon/public key
//
// PRODUCTION: This file is auto-generated by GitHub Actions from repository
//   secrets SUPABASE_URL and SUPABASE_ANON — do not commit real credentials.
// ──────────────────────────────────────────────────────────────────────────────

//var SUPABASE_URL1  = 'SUPABASE_URL';
//var SUPABASE_ANON1 = 'SUPABASE_ANON'; // ← paste your anon/public key from Supabase Dashboard → Settings → API
 

var SUPABASE_URL1 ='https://tjpxkzpqauffyzcpfvyi.supabase.co';
var SUPABASE_ANON1 = 'sb_publishable_7M5R0Gt_k6x9aBhD-qgElQ_rX-pop-C';
var _supabase = (function () {
  if (!SUPABASE_URL1.startsWith('https://') || SUPABASE_ANON1.length < 20) {
    console.error('[LM] supabase-config.js: SUPABASE_URL or SUPABASE_ANON not configured. Edit auth/supabase-config.js with your real credentials.');
    return undefined;
  }
  return window['supabase'].createClient(SUPABASE_URL1, SUPABASE_ANON1, {
    auth: {
      persistSession    : true,
      autoRefreshToken  : true,
      detectSessionInUrl: true
    }
  });
}());
